name: Daily Scraper Update

on:
  schedule:
    - cron: '30 6 * * *'  # Runs daily at 12:00 PM IST
  workflow_dispatch:      # Allow manual trigger too

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run scraper
      run: python run.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add output/ data/
       - name: Commit and push changes
  run: |
    git config user.name "github-actions"
    git config user.email "github-actions@github.com"
    git add output/ data/
    git diff --cached --quiet && echo "✅ No changes to commit" || (git commit -m "🔄 Auto-update scraped content" && git push)
    git push
